#
# Copyright (c) 2026 Jon Sharp
#
# SPDX-License-Identifier: Apache-2.0
#
# US DECT band carrier and a reduced transmit power. Only operate on the DECT
# band if you are permitted to and can ensure local access rules are met;
# otherwise prevent radio emissions (for example, with an RF chamber).
#
CONFIG_DECT_MESH_CARRIER=1711
CONFIG_DECT_MESH_TX_POWER=10
