#
# Copyright (c) 2026 Jon Sharp
#
# SPDX-License-Identifier: Apache-2.0
#
# EU DECT band carrier. Only operate on the DECT band if you are permitted to
# and can ensure local access rules are met; otherwise prevent radio emissions
# (for example, with an RF chamber).
#
CONFIG_DECT_MESH_CARRIER=1677
